services:
  - type: web
    name: strapi-backend
    env: node
    rootDir: strapi-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: better-sqlite3
      - key: POSTCSS_CONFIG_PATH
        value: ""
